apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port