apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these labels are replicaset labels
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine3.23-perl