apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these labels are replicaset labels
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
  annotations:
    kubernetes.io/change-cause: "moving to 1.29.7"
spec:
  replicas: 4
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.7
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    # labels are used as selectors
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port